# The Docker image that will be used to build your app
image: node:20-slim

variables:
  http_proxy: http://cache.univ-nantes.fr:3128/
  https_proxy: http://cache.univ-nantes.fr:3128/

# Functions that should be executed before the build script is run
before_script:
  - npm install
pages:
  script:
    - npx quasar build -d
    - cp -a dist/spa/ public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
