# The Docker image that will be used to build your app
image: node:20-slim

# Functions that should be executed before the build script is run
before_script:
  # Needed for electron
  - export ELECTRON_GET_USE_PROXY=true
  - export GLOBAL_AGENT_HTTPS_PROXY=$https_proxy
  - npm config set proxy $http_proxy
  - npm config set https-proxy $https_proxy
  - npm install
pages:
  script:
    - npx quasar build -d
    - git describe --always || echo "Error in git describe: $?"
    - /bin/rm -rf public/assets
    - cp -a dist/spa/assets public/assets
    - cp dist/spa/index.html public/index.html
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
