# The Docker image that will be used to build your app
image: node:20-slim

# Functions that should be executed before the build script is run
before_script:
  - export ELECTRON_GET_USE_PROXY=true
  - export GLOBAL_AGENT_HTTPS_PROXY=$https_proxy
  - npm config set proxy $http_proxy
  - npm config set https-proxy $https_proxy
  - npm install
pages:
  script:
    - npx quasar build -d
    - cp -a dist/spa/ public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
