# Deploy the μPMT application to Github Pages
name: Deploy μPMT application

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "gh-pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build
        run: npx quasar build -d

      - name: Prepare target dir
        run: |
          set -e
          BRANCH="${GITHUB_REF_NAME}"
          if [ "$BRANCH" = "main" ]; then
            TARGET_DIR="."
          elif [ "$BRANCH" = "dev" ]; then
            TARGET_DIR="dev"
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi

          # stage output we want to publish
          rm -rf publish
          mkdir -p "publish/${TARGET_DIR}"

          # copy built SPA into publish/${TARGET_DIR}
          cp -a dist/spa/* "publish/${TARGET_DIR}/"

          # copy examples
          cp -a examples/ publish/${TARGET_DIR}/examples/

          # version file per branch
          echo "${GITHUB_SHA}" > "publish/${TARGET_DIR}/version.txt"

      - name: Deploy to gh-pages (keep both main + dev)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: publish
          # preserve the other branch’s directory when updating one.
          keep_files: true
